name: CI/CD for Angular App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: List contents of dist directory
        run: |
          echo "Listing the contents of the dist folder:"
          ls -alh ./

      - name: Install dependencies
        run: |
            cd TVNBhavani 
            npm install


      - name: Build the Angular project
        run: |
            cd TVNBhavani 
            npm run build -- --configuration production

      - name: Install angular-cli-ghpages
        run: |
            cd TVNBhavani 
            npm install -g angular-cli-ghpages

      - name: Configure Git user
        run: |
          git config --global user.email "vt325@njit.edu"
          git config --global user.name "TVNBhavani"

      - name: List contents of dist directory
        run: |
          echo "Listing the contents of the dist folder:"
          ls -alh ./TVNBhavani/dist


      - name: Set permissions for dist folder
        run: chmod -R 777 ./TVNBhavani/dist/TVNBhavani

      - name: Deploy to GitHub Pages
        run: |
          cd TVNBhavani
          npx angular-cli-ghpages --dir=./dist/TVNBhavani/ --repo=https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/TVNBhavani/TVNBhavani.git --branch=gh-pages --no-silent
          